mode:
  mode: "local"
  overlay_interface: null
  https_enabled: false
  tls_cert_path: null
  tls_key_path: null
  google_oauth_client_id: null
  google_oauth_client_secret: null
  google_allowed_emails: []
api:
  bind_host: "127.0.0.1"
  port: 8008
  require_api_key: false
  api_key: null
  rate_limit_rps: 2.0
  rate_limit_burst: 5
  max_page_size: 200
  default_page_size: 50
  max_query_chars: 2000
  max_context_k: 50
offline: true
privacy:
  cloud_enabled: false
  sanitize_default: true
  extractive_only_default: true
  paused: false
  snooze_until_utc: null
  exclude_monitors: []
  exclude_processes: []
  exclude_window_title_regex: []
  exclude_regions: []
routing:
  capture: "local"
  ocr: "local"
  embedding: "local"
  retrieval: "local"
  reranker: "disabled"
  compressor: "extractive"
  verifier: "rules"
  llm: "ollama"
llm:
  provider: "ollama"
  ollama_url: "http://127.0.0.1:11434"
  ollama_model: "llama3"
  openai_api_key: null
  openai_model: "gpt-4.1-mini"
  timeout_s: 60.0
  retries: 3
promptops:
  enabled: false
  schedule_cron: "0 6 * * 1"
  sources: []
  github_token: null
  github_repo: null
capture:
  hid:
    min_interval_ms: 500
    idle_grace_ms: 1500
    duplicate_threshold: 0.02
    duplicate_window_s: 10.0
    duplicate_max_items: 16
    duplicate_pixel_threshold: 2.5
    fps_soft_cap: 4.0
    block_fullscreen: true
  fps_min: 0.5
  fps_max: 2.0
  tile_size: 512
  diff_epsilon: 0.04
  downscale_width: 256
  always_store_fullres: true
  thumbnail_width: 640
  staging_dir: "D:/autocapture/staging"
  data_dir: "D:/autocapture/data"
  encoder: "nvenc_webp"
  record_video: true
  layout_mode: "virtual_desktop"
  video_bitrate: "8M"
  video_preset: "p4"
  max_pending: 8000
ocr:
  queue_maxsize: 4000
  batch_size: 32
  max_latency_s: 900
  engine: "rapidocr-onnxruntime"
  device: "cuda"
  languages: ["en"]
  output_format: "json"
embed:
  text_model: "BAAI/bge-base-en-v1.5"
  image_model: "google/siglip2-so400m-patch14-384"
  text_batch_size: 256
  image_batch_size: 32
  schedule_cron: "0 */6 * * *"
  use_half_precision: true
reranker:
  enabled: true
  model: "BAAI/bge-reranker-v2-m3"
  top_k: 100
worker:
  data_dir: "D:/autocapture/data"
  lease_ms: 60000
  ocr_lease_ms: 60000
  embedding_lease_ms: 60000
  poll_interval_s: 1.0
  ocr_backlog_soft_limit: 5000
  ocr_max_attempts: 5
  ocr_workers: 4
  embed_workers: 1
  embedding_max_attempts: 5
storage:
  image_quota_gb: 2500
  prune_grace_days: 90
  prune_batch: 3000
retention:
  video_days: 3
  roi_days: 14
  max_media_gb: 200
  screenshot_ttl_days: 90
database:
  url: "sqlite:///D:/autocapture/data/autocapture.db"
  echo: false
  pool_size: 10
  max_overflow: 10
qdrant:
  enabled: true
  url: "http://127.0.0.1:6333"
  text_collection: "text_spans"
  image_collection: "image_tiles"
  text_vector_size: 768
  image_vector_size: 768
  distance: "Cosine"
  hnsw_ef_construct: 128
  hnsw_m: 16
  search_ef: 64
ffmpeg:
  enabled: true
  require_bundled: true
  relative_path_candidates:
    - "ffmpeg/bin/ffmpeg.exe"
    - "ffmpeg/ffmpeg.exe"
encryption:
  enabled: true
  key_provider: "windows-credential-manager"
  key_name: "autocapture/nas-aes-key"
  chunk_size: 4194304
observability:
  prometheus_bind_host: "127.0.0.1"
  prometheus_port: 9005
  prometheus_port_fallbacks: 10
  prometheus_fail_fast: false
  grafana_url: "http://tnas:3000"
  enable_gpu_stats: true
